export default {
  BACKGROUND: require('../assets/background.png'),
  DONE_IMG: require('../assets/done.png'),
  INFOMATION_IMG: require('../assets/information.png'),
  LOGO_ALTA_MEDIA: require('../assets/logo.png'),
  ALTA_MEDIA_VIDEO: require('../assets/alta_video.png'),
  ICON_SCAN: require('../assets/icon_scan.png'),
  ARROW_RIGHT: require('../assets/arrow_right.png'),
  ERROR_CARD: require('../assets/error_card.png'),
  OUT_OF_NOODLES: require('../assets/out_of_noodles.png'),
  ARROW_DOWN: require('../assets/arrow_down.png'), 
  BORDER_VIDEO_ALTA : require('../assets/border_video_alt.png'), 
  SCAN_LOGIN: require('../assets/scan_area.png'),
  DEFAULT_USER_IMG: require('../assets/default_user_image.png'),
  BUTTON_BACKGROUND: require('../assets/button_background.png'),
  NOODLE_LEFT: require('../assets/noodleLeft.png'),
  NOODLE_MIDDLE: require('../assets/noodleMiddle.png'),
  NOODLE_RIGHT: require('../assets/noodleRight.png'),
  NOODLE_UNAVAILABLE : require('../assets/noodleUnavailable.png'),
  IS_SELECTED: require('../assets/isSelected.png'),
  HEART_ICON :  require('../assets/heart_icon.png'),
  BACKGROUND_TEXT :  require('../assets/background_text.png'),
}