export default {
  BACKGROUND: require('../assets/background.png'),
  DONE_IMG: require('../assets/done.png'),
  ERROR_IMG: require('../assets/error.png'),
  INFOMATION_IMG: require('../assets/information.png'),
  LOGO_ALTA_MEDIA: require('../assets/logo.png'),
  OUT_OF_NOODLES_IMG: require('../assets/out_of_noodles.png'),
  ALTA_MEDIA_VIDEO: require('../assets/alta_video.png'),
  ICON_SCAN: require('../assets/icon_scan.png'),
  DOUBLE_ARROW_RIGHT: require('../assets/double_arrow.png'),
  ERROR_CARD: require('../assets/error_card.png'),
  OUT_NOODLES_CUP: require('../assets/out_noodles.png'),
  THREE_CUP_OF_NOODLES_LEFT_THIS_MONTH: require('../assets/3_cups_of_noodles_left_this_month.png'),
  BTN_GET_NOODLES: require('../assets/btn_get_noodles.png'),
  BTN_BACK_TO_HOME: require('../assets/btn_back_to_home.png'),
  DOUBLE_ARROW_DOWN: require('../assets/double_arrow_down.png'), 
  BORDER_VIDEO_ALTA : require('../assets/border_video_alt.png'), 
  SCAN_LOGIN: require('../assets/scan_area.png'),
}